server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/microsoft_ai
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          azure:
            provider: azure
            client-id: ${AAD_CLIENT_ID}
            client-secret: ${AAD_CLIENT_SECRET}
            scope: openid, profile, email, offline_access, https://graph.microsoft.com/User.Read
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          azure:
            authorization-uri: "https://login.microsoftonline.com/${AAD_TENANT_ID}/oauth2/v2.0/authorize"
            token-uri: "https://login.microsoftonline.com/${AAD_TENANT_ID}/oauth2/v2.0/token"
            jwk-set-uri: "https://login.microsoftonline.com/${AAD_TENANT_ID}/discovery/v2.0/keys"
            user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
            user-name-attribute: name

      resourceserver:
        jwt:
          issuer-uri: "https://login.microsoftonline.com/${AAD_TENANT_ID}/v2.0"


app:
  security:
    expected-audience: "api://84917c93-a6b1-4ded-bea2-5efa1e6a6476"

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
